name: release

on:
  push:
    on:
    -  cron:  '20 10 * * *' 
    branches:
    - '*'
    tags:
    - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.toolkit-meta.outputs.tags }}
      digest: ${{ steps.build-toolkit.outputs.digest }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for toolkit image
        id: toolkit-meta
        uses: docker/metadata-action@v4
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=semver,pattern={{version}}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache

      - name: Build toolkit image
        id: build-toolkit
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.toolkit-meta.outputs.tags }}
          labels: ${{ steps.toolkit-meta.outputs.labels }}
          file: ./Dockerfile
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  sign:
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions: 
      packages: write
      id-token: write
    outputs:
      tags: ${{ steps.web-meta.outputs.tags }}
    steps:
      - uses: sigstore/cosign-installer@main

      - name: Login to GitHub Container Registry for cosign
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        run: |
          cosign sign -y \
            -a "repo=${{ github.repository }}" \
            -a "workflow=${{ github.workflow }}" \
            -a "ref=${{ github.sha }}" \
            -a "actor=${{ github.actor }}" \
            ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit@${{ needs.build.outputs.digest }}
        env:
          COSIGN_PASSWORD: ""
