name: release

on:
  push:
    on:
    -  cron:  '20 10 * * *' 
    branches:
    - '*'
    tags:
    - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      tags: ${{ steps.toolkit-meta.outputs.tags }}
      digest: ${{ steps.build-toolkit.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for toolkit image
        id: toolkit-meta
        uses: docker/metadata-action@v5
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=semver,pattern={{version}}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache

      - name: Build toolkit image
        id: build-toolkit
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.toolkit-meta.outputs.tags }}
          labels: ${{ steps.toolkit-meta.outputs.labels }}
          file: ./Dockerfile
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

  provide-sbom:
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions: 
      packages: write
      id-token: write
    steps:
      - uses: sigstore/cosign-installer@v3.1.2

      - name: Login to GitHub Container Registry for cosign
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM
        id: generate-sbom
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit

      - name: Attach SBOM to image
        run: |
          ls -la
          cosign attach sbom --sbom crdant-replicated-toolkit.spdx.json \
            ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit@${{ needs.build.outputs.digest }}
        env:
          COSIGN_PASSWORD: ""

      - name: Sign SBOM
        run: |
          cosign sign -y \
            --attachment sbom ${{ github.repository }}-provide-sbom-generate-sbom.spdx.json \
            -a "githubWorkflowActor=${{ github.actor }}" \
            ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit@${{ needs.build.outputs.digest }}
        env:
          COSIGN_PASSWORD: ""


  sign:
    runs-on: ubuntu-22.04
    needs:
      - build
      - provide-sbom
    permissions: 
      packages: write
      id-token: write
    steps:
      - uses: sigstore/cosign-installer@v3.1.2

      - name: Login to GitHub Container Registry for cosign
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        run: |
          cosign sign -y \
            -a "githubWorkflowActor=${{ github.actor }}" \
            ${{ env.REGISTRY }}/${{ github.actor }}/replicated-toolkit@${{ needs.build.outputs.digest }}
        env:
          COSIGN_PASSWORD: ""
